"""empty message

Revision ID: 8d485b805e2a
Revises: None
Create Date: 2016-04-18 19:31:28.504031

"""

# revision identifiers, used by Alembic.
revision = '8d485b805e2a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ability_score_points',
    sa.Column('ability_score_point_id', sa.Integer(), nullable=False),
    sa.Column('campaign_type', sa.String(length=20), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ability_score_point_id'),
    sa.UniqueConstraint('campaign_type')
    )
    op.create_table('bonus_spells',
    sa.Column('bonus_spell_id', sa.Integer(), nullable=False),
    sa.Column('ability_modifier', sa.Integer(), nullable=True),
    sa.Column('first_level', sa.Integer(), nullable=True),
    sa.Column('second_level', sa.Integer(), nullable=True),
    sa.Column('third_level', sa.Integer(), nullable=True),
    sa.Column('fourth_level', sa.Integer(), nullable=True),
    sa.Column('fifth_level', sa.Integer(), nullable=True),
    sa.Column('sixth_level', sa.Integer(), nullable=True),
    sa.Column('seventh_level', sa.Integer(), nullable=True),
    sa.Column('eighth_level', sa.Integer(), nullable=True),
    sa.Column('ninth_level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('bonus_spell_id'),
    sa.UniqueConstraint('ability_modifier')
    )
    op.create_table('carrying_capacities',
    sa.Column('carrying_capacity_id', sa.Integer(), nullable=False),
    sa.Column('strength_score', sa.Integer(), nullable=True),
    sa.Column('light_load', sa.String(length=20), nullable=True),
    sa.Column('medium_load', sa.String(length=20), nullable=True),
    sa.Column('heavy_load', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('carrying_capacity_id')
    )
    op.drop_table('carrying_capacity')
    op.drop_table('ability_score_point')
    op.drop_table('bonus_spell')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bonus_spell',
    sa.Column('bonusspellid', sa.INTEGER(), nullable=False),
    sa.Column('abilitymodifier', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('firstlevel', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('secondlevel', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('thirdlevel', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fourthlevel', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fifthlevel', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sixthlevel', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('seventhlevel', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('eighthlevel', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ninthlevel', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('bonusspellid', name=u'bonus_spell_pkey'),
    sa.UniqueConstraint('abilitymodifier', name=u'bonus_spell_abilitymodifier_key')
    )
    op.create_table('ability_score_point',
    sa.Column('abilityscorepointid', sa.INTEGER(), server_default=sa.text(u'nextval(\'"ability_score_point_AbilityScorePointsID_seq"\'::regclass)'), nullable=False),
    sa.Column('campaigntype', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('abilityscorepointid', name=u'ability_score_point_pkey'),
    sa.UniqueConstraint('campaigntype', name=u'ability_score_point_CampaignType_key')
    )
    op.create_table('carrying_capacity',
    sa.Column('carrying_capacity_id', sa.INTEGER(), nullable=False),
    sa.Column('strength_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('light_load', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('medium_load', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('heavy_load', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('carrying_capacity_id', name=u'carrying_capacity_pkey')
    )
    op.drop_table('carrying_capacities')
    op.drop_table('bonus_spells')
    op.drop_table('ability_score_points')
    ### end Alembic commands ###
