"""empty message

Revision ID: 9336b2f5a1c7
Revises: 8d485b805e2a
Create Date: 2016-04-18 20:04:55.163313

"""

# revision identifiers, used by Alembic.
revision = '9336b2f5a1c7'
down_revision = '8d485b805e2a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aging_effects',
    sa.Column('aging_effects_id', sa.Integer(), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('dexterity', sa.Integer(), nullable=True),
    sa.Column('constitution', sa.Integer(), nullable=True),
    sa.Column('intelligence', sa.Integer(), nullable=True),
    sa.Column('wisdom', sa.Integer(), nullable=True),
    sa.Column('charisma', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('aging_effects_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aging_effects')
    ### end Alembic commands ###
